CREATE DATABASE IF NOT EXISTS ${DB_NAME};
CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
use ${DB_NAME};UPDATE user SET Password=PASSWORD('${DB_ROOT_PASSWORD}') WHERE user='root';
        UPDATE user SET plugin = '' WHERE user = 'root';FLUSH PRIVILEGES;